### ISSUE TITLE
mamba env create guppy doesn't work

### ISSUE THREAD

**Issue by DelphIONe** [comprna/METEORE#11]
I have some problem with this command, can you help me again ?

mamba env create -f guppy.yml

Encountered problems while solving.
Problem: package r-plyr-1.8.6-r36h0357c0b_1 requires r-base >=3.6,<3.7.0a0, but none of the providers can be installed
Problem: package r-dplyr-1.0.2-r36h0357c0b_0 requires r-base >=3.6,<3.7.0a0, but none of the providers can be installed
Problem: package r-data.table-1.13.0-r36h0eb13af_0 requires r-base >=3.6,<3.7.0a0, but none of the providers can be installed

Thanks

**Comment by zakayuen** [comment]
Hi,

Once you activate the guppy environment, you can install these packages with Conda by running these:
```
conda install -c conda-forge r-plyr r-dplyr
conda install -c r r-data.table
```

Hope this helps.

Cheers
Zaka
