### ISSUE TITLE
Hello,professor！I can't find .fast5 which contained in dataset1&dataset2 

### ISSUE THREAD

**Issue by Bessyyi** [comprna/METEORE#16]
Dear,professor！
  when i repeat your article,i can't find the file .fast5 which contained in mixture dataset  in (ERR1676719 for negative control and ERR1676720 for positive control).  Did you just use two run(ERR1676719&ERR1676720)or any other run？

**Comment by cameron-jack** [comment]
It's just those two runs. You'll have to uncompress the .tar.gz file.
