### ISSUE TITLE
It's just those two runs. You'll have to uncompress the .tar.gz file.

### ISSUE THREAD

**Issue by Bessyyi** [comprna/METEORE#17]
It's just those two runs. You'll have to uncompress the .tar.gz file.

_Originally posted by @cameron-jack in https://github.com/comprna/METEORE/issues/16#issuecomment-882942145_

**Comment by Bessyyi** [comment]
Thank you for your replay,I have used 'tar -xzvf ' to uncompress the file ，but i could not  find them .What's more,when i  finish uncompress ,my fast5 become green file .Can you give me some advice? Thank you very much!

**Comment by cameron-jack** [comment]
These files show up as green because their attributes are "executable". Can you please run:
<code>
ls -lh
</code>
in the directory where you uncompressed the files? Then copy and paste what you are seeing, so I can see what you are dealing with? Thanks

**Comment by Bessyyi** [comment]
> These files show up as green because their attributes are "executable". Can you please run:
> ` ls -lh `
> in the directory where you uncompressed the files? Then copy and paste what you are seeing, so I can see what you are dealing with? Thanks
Here are my results(fig1).When i guppy them i get the error that shows in fig2
![11](https://user-images.githubusercontent.com/73151161/126262712-257faa96-6952-4292-b20b-087518e57098.PNG)
![2](https://user-images.githubusercontent.com/73151161/126262911-d0f3a64c-d682-4efa-807c-e7922aea4b04.PNG)

**Comment by zakayuen** [comment]
I have attached a python script ([addAttr_fixData_inF5.txt](https://github.com/comprna/METEORE/files/6852695/addAttr_fixData_inF5.txt)) to fix the attributes from the fast5 files. Please convert _.txt_ to _.py_ before running the script in the terminal. 

To run it, you first go to the directory containing nanopore reads in FAST5 format, 

`cd your_fast5_directory/`

then run 

`python path_to_the_python_script/addAttr_fixData_inF5.py`

It should fix the fast5 files. I will add this script to METEORE as well.

Zaka
