### ISSUE TITLE
Problems running the Nanopolish example: libcrypto.so.1.0.0: 

### ISSUE THREAD

**Issue by NiRuff** [comprna/METEORE#19]
Hi, @zakayuen,

I ran into a problem while samtools_sort after running the following line of your Nanopore example:

```
snakemake -s Nanopolish nanopolish_results/example_nanopolish-freq-perCG.tsv --cores all
```

Installation actually seems to have worked fine - I tried both, the .yml file and installation using mamba.

(meteore_nanopolish_env) nicolas@nicolas-Precision-7820-Tower:~/Programs/METEORE$ snakemake -s Nanopolish nanopolish_results/example_nanopolish-freq-perCG.tsv --cores all
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 40
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job counts:
	count	jobs
	1	calculate_frequency
	1	call_methylation
	1	index
	1	minimap2
	1	samtools_index
	1	samtools_sort
	1	split_cpgs
	7

[Thu Sep 16 10:55:20 2021]
rule minimap2:
    input: data/ecoli_k12_mg1655.fasta, example.fastq
    output: nanopolish_results/mapped/example.bam
    log: nanopolish_results/mapped/example.log
    jobid: 6
    wildcards: sample=example
    threads: 6

[Thu Sep 16 10:55:20 2021]
rule index:
    input: data/example, example.fastq
    output: example.fastq.index, example.fastq.index.fai, example.fastq.index.gzi, example.fastq.index.readdb
    jobid: 5
    wildcards: sample=example

[readdb] indexing data/example
[readdb] num reads: 50, num reads with path to fast5: 50
[Thu Sep 16 10:55:20 2021]
Finished job 5.
1 of 7 steps (14%) done
[Thu Sep 16 10:55:21 2021]
Finished job 6.
2 of 7 steps (29%) done

[Thu Sep 16 10:55:21 2021]
rule samtools_sort:
    input: nanopolish_results/mapped/example.bam
    output: nanopolish_results/mapped/example.sorted.bam
    jobid: 3
    wildcards: sample=example

samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[Thu Sep 16 10:55:21 2021]
Error in rule samtools_sort:
    jobid: 3
    output: nanopolish_results/mapped/example.sorted.bam
    shell:
        samtools sort -o nanopolish_results/mapped/example.sorted.bam nanopolish_results/mapped/example.bam
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/nicolas/Programs/METEORE/.snakemake/log/2021-09-16T105520.230639.snakemake.log

Best,
Nicolas

**Comment by NiRuff** [comment]
Now trying mamba installation another time, I saw an error occurrin there:

Encountered problems while solving:
  - nothing provides openmp needed by nanopolish-0.10.1-h78a5b34_0


However, when using the .yml installation, no error occurs but there I run into the above given problem.

Best,
Nicolas

**Comment by zakayuen** [comment]
Hi Nicolas,

It seems like it is a conda issue. 

Can you please try reinstall `samtools` in your Nanopilish environment? 

 `conda install -c bioconda samtools=1.9 --force-reinstall`

Then rerun the snakemake pipeline again.

Let me know if it solves the issue.

Zaka
