### ISSUE TITLE
Module Not Found Error: import in call_modification_frequency.py

### ISSUE THREAD

**Issue by ViHammer** [comprna/METEORE#2]
I am currently trying to run your 'call_modification_frequency.py' script on deepsignal data I have. This is the error message it produces:
```
Traceback (most recent call last):
  File "call_modification_frequency.py", line 10, in <module>
    from txt_formater import ModRecord
ModuleNotFoundError: No module named 'txt_formater'
```
I cannot find any module with this name online. 

Thanks in advance!

**Comment by zakayuen** [comment]
Hi,

What command did you use to run this script? Please also check if there is a file called `txt_formater.py` under the `script_in_snakemake` directory so that you can import the `ModRecord` submodule from the `txt_formater` module.

Zaka

**Comment by ViHammer** [comment]
Hi, I tried running the script independently from your pipeline and forgot to move the `txt_formater.py` file with my script.
It works now!
