### ISSUE TITLE
Issue with downloading E.coli Nanopore data 

### ISSUE THREAD

**Issue by onkar2470** [comprna/METEORE#21]
Hi,
I downloaded E.coli nanopore data which is required to generate dataset1 from the European Nucleotide Archive (ENA) under accession PRJEB13021 (ERR1676719 for negative control and ERR1676720 for positive control) using wget command. The files were fully downloaded according to logs from wget.

wget commands : 
wget -c --tries=0 ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR167/ERR1676720/ecoli_er2925.pcr_MSssI.r9.timp.061716.tar.gz
wget -c --tries=0 ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR167/ERR1676719/ecoli_er2925.pcr.r9.timp.061716.tar.gz

But while decompressing the downloaded files using tar, it is showing error like **'gzip: stdin: invalid compressed data--format violated'** and ending the decompress process.

tar commands : 
tar xvzf ecoli_er2925.pcr.r9.timp.061716.tar.gz
tar xvzf ecoli_er2925.pcr_MSssI.r9.timp.061716.tar.gz

This happened with both the files negative as well as positive control.

Also md5 values for original file and downloaded are different ensuring problem with the downloaded file.

Is there any better way to download these files? **Or if possible can you provide the file containing fast5 files from dataset1 that you have used for your analysis?**

Thank you,
Regards,
Onkar

**Comment by Bessyyi** [comment]
I get the same question,can you give me some suggestions about it.

**Comment by EduEyras** [comment]
Hi,

If your md5 values are different, there was probably a problem with the download.

The error “gzip: stdin"usually occurs when the file is not in the gzip format. 

It could be that the file is not actually .gz or that it was named tar.gz but it used a different compression. 

You could try the command "file" on the filename, to see whether the format is the expected one. 

I hope this helps

E.
