### ISSUE TITLE
Problem running DeepMod on exmaple data!!!

### ISSUE THREAD

**Issue by onkar2470** [comprna/METEORE#22]
Hi,
I am running DeepMod-0.1.3 on example data provided. But it is showing error and giving no output.
Following is the log file for deepmod run : 

Nanopore sequencing data analysis is resourece-intensive and time consuming. 
Some potential strong recommendations are below:
	If your reference genome is large as human genome and your Nanopore data is huge,
	It would be faster to run this program parallelly to speed up.
	You might run different input folders of your fast5 files and 
	give different output names (--FileID) or folders (--outFolder)
	A good way for this is to run different chromosome individually.

             Current directory: example_data/METEORE-1.0.0/data
                      outLevel: 2
                       wrkBase: example
                        FileID: ecoli_deepmod
                     outFolder: ecoli_deepmod/
                     recursive: 1
              files_per_thread: 1000
                       threads: 15
                    windowsize: 21
                      alignStr: minimap2
                   SignalGroup: simple
                          move: False
                   basecall_1d: Basecall_1D_000
              basecall_2strand: BaseCalled_template
                        ConUnk: True
                   outputlayer: 
                          Base: C
                   mod_cluster: 0
                       predDet: 1
                           Ref: ecoli_k12_mg1655.fasta
                          fnum: 7
                        hidden: 100
                       modfile: DeepMod-0.1.3/train_deepmod/rnn_sinmodC_P100wd21_f7ne1u0_4/mod_train_sinmodC_P100wd21_f3ne1u0
                        region: [[None, None, None]]

Instructions for updating:
Use standard file APIs to check for files with this prefix.
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch114_read6906_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch294_read732_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch177_read479_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch279_read13169_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch354_read2006_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch230_read20744_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch172_read1102_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch158_read435_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch262_read814_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch330_read2145_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch324_read570_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch217_read1495_strand1.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch258_read2664_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch294_read356_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch118_read2334_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch412_read8784_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch269_read2204_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch433_read26717_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch118_read526_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch381_read12341_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch298_read2348_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch88_read4943_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch252_read2417_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch366_read1770_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch159_read630_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch324_read1332_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch313_read2657_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch241_read2385_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch434_read696_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch139_read4507_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch175_read80_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch436_read2992_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch311_read1440_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch430_read511_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch422_read940_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch375_read1018_strand1.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch270_read545_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch193_read10923_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch431_read800_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch224_read1419_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch409_read716_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch418_read3292_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch138_read698_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch228_read1212_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch162_read1065_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch142_read2358_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch291_read161080_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch443_read162_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch375_read1189_strand.fast5
Error!!! No events data in example/kelvin_20160617_FN_MN17519_sequencing_run_sample_id_74930_ch205_read3886_strand.fast5
[M::mm_idx_gen::0.128*1.18] collected minimizers
[M::mm_idx_gen::0.159*1.52] sorted minimizers
[M::main::0.159*1.52] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.181*1.46] mid_occ = 12
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.190*1.44] distinct minimizers: 838542 (98.18% are singletons); average occurrences: 1.034; average spacing: 5.352
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax map-ont ecoli_k12_mg1655.fasta /tmp/tmp19jlkpxt.fa
[M::main] Real time: 0.194 sec; CPU: 0.277 sec; Peak RSS: 0.382 GB
Cur Prediction consuming time 1 for 0 0
Error information for different fast5 files:
	No events data 50
Per-read Prediction consuming time 8
Find: ecoli_deepmod//ecoli_deepmod 0 rnn.pred.ind
[]
Genomic-position Detection consuming time 0

**I checked fast5 files using h5ls -r command. fastq and event dataset can be found in the /Analyses/Basecall_1D_000/BaseCalled_template/ group. but deepmod is not able to find it. Can you comment whats happening here?Is this fast5 file problem or am I missing some step?**

Thank you 

Regards 
Onkar

**Comment by zakayuen** [comment]
I am really sorry for the late reply. 

I would suggest using other tools than DeepMod as it doesn't have high accuracy like the other tools.

Back then when I ran DeepMod, I got the issue like yours saying that there is no event info in fast5. I solved this by adding --move and --basecall_1d Basecall_1D_001 to the command. 

Zaka
