### ISSUE TITLE
Deepsignal1 snakemake file -  error with example data 

### ISSUE THREAD

**Issue by martinastoycheva** [comprna/METEORE#25]
Hello,

Thanks for creating this handy pipeline! I tried running the software with your example data and it ran fine with nanopolish but I am encountering an error when I try running the Deeepsignal1. I have created the environment following your instructions and the software installed fine. I also downloaed and extracted the model files in the data directory. However, I get an error:

`
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	calculate_frequency
	1	call_modification
	2

[Wed May  4 15:38:22 2022]
rule call_modification:
    input: deepsignal_results/example_deepsignal-feature.tsv
    output: deepsignal_results/example_deepsignal-prob.tsv
    jobid: 1
    wildcards: sample=example

Traceback (most recent call last):
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/bin/deepsignal", line 8, in <module>
    sys.exit(main())
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/deepsignal/deepsignal.py", line 424, in main
    args.func(args)
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/deepsignal/deepsignal.py", line 46, in main_call_mods
    from .call_modifications import call_mods
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/deepsignal/call_modifications.py", line 10, in <module>
    import tensorflow as tf
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so)
[Wed May  4 15:38:23 2022]
Error in rule call_modification:
    jobid: 1
    output: deepsignal_results/example_deepsignal-prob.tsv

RuleException:
CalledProcessError in line 16 of /mnt/lustre/groups/biol-ralsto-2019/SOFTWARE/METEORE/Deepsignal1:
Command ' set -euo pipefail;  deepsignal call_mods --input_path deepsignal_results/example_deepsignal-feature.tsv --is_gpu no --nproc 10 --model_path data/model.CpG.R9.4_1D.human_hx1.bn17.sn360.v0.1.7+/bn_17.sn_360.epoch_9.ckpt --result_file deepsignal_results/example_deepsignal-prob.tsv ' returned non-zero exit status 1.
  File "/mnt/lustre/groups/biol-ralsto-2019/SOFTWARE/METEORE/Deepsignal1", line 16, in __rule_call_modification
  File "/users/mms565/scratch/conda/envs/meteore_deepsignal_env1/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/lustre/groups/biol-ralsto-2019/SOFTWARE/METEORE/.snakemake/log/2022-05-04T153822.867032.snakemake.log
`

**Comment by zakayuen** [comment]
I will try to reproduce the errors you have and see how I can fix these.

Zaka

**Comment by zakayuen** [comment]
Can you please let me know which versions of `python`, `snakemake`, `tensorflow,` `ont-fast5-api` and `ont-tombo` you are using in the environment?

You can check the version with this command:
`conda list| grep "python\|snakemake\|ont-\|tensorflow"`

`Deepsignal1` works with the packages with the following versions:
- python 3.6.1
- snakemake 5.3.0
- tensorflow 1.13.1
- ont-fast4-api 4.0.2
- ont-tombo 1.5.1

If you have a different version of the package, please remove the current environment and create the Conda environment again. 

Hope this helps.

**Comment by martinastoycheva** [comment]
Hello, 
Thank you for your help! It seems to me like the software versions are correct:

- ont-fast5-api             4.0.2                    pypi_0    pypi
- ont-tombo                 1.5.1                    pypi_0    pypi
- python                    3.6.1                         3    conda-forge
- python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
- python-irodsclient        1.1.3              pyhd8ed1ab_0    conda-forge
- python_abi                3.6                     2_cp36m    conda-forge
- snakemake                 5.3.0                    py36_1    bioconda
- snakemake-minimal         5.3.0                    py36_1    bioconda
- tensorflow                1.13.1                   pypi_0    pypi
- tensorflow-estimator      1.13.0                   pypi_0    pypi

Cheers, 
Martina

**Comment by zakayuen** [comment]
The versions are indeed the same. Let's try another way.

Can you please try to add the path to the lib folder in miniconda to LD_LIBRARY_PATH:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/path/to/miniconda/lib`

Try to rerun Deepsignal1 to see if this works.

Zaka

**Comment by martinastoycheva** [comment]
Hello Zaka, 

This solved the issue! Thank you very much!
