### ISSUE TITLE
Can Nanopolish snakemake call cpggpc pattern?

### ISSUE THREAD

**Issue by kir1to455** [comprna/METEORE#29]
Hi, I noticed that Nanopolish snakemake code.
`snakemake -s Nanopolish nanopolish_results/example_nanopolish-freq-perCG.tsv --cores all`
Can I choose the pattern (CpG/GpC/cpggpc) in this snakemake ,or it only work for calling CpG?

Best wishes,
Kirtio

**Comment by zakayuen** [comment]
Hi Kirtio,

To my knowledge, Nanopolish can only detect CpG methylation.

Zaka
