### ISSUE TITLE
[BUG] Incorrect score in script/format_megalodon.R

### ISSUE THREAD

**Issue by richardstoeckl** [comprna/METEORE#32]
Hi, thank you for this great tool!

I think I noticed a tiny mistake in the [format_megalodon.R](https://github.com/comprna/METEORE/blob/ba8e517c51dbfd3fea5130f297c480c4626c2ff0/script/format_megalodon.R) script.

In line 15, the df is reduced to six columns. In line 16, a new column "Score" is introduced -> the 7th column.
However, in line 17, columns 1,2,3,4, and 6 are kept and in line 18 the sixth column ist renamed to "Score" while it is in fact the "can_log_prob"

```R
df <- df %>% select(1,2,4,3,5,6)
df$Score <- df$mod_log_prob - df$can_log_prob
df <- df %>% select(1,2,3,4,6)
colnames(df) <- c("ID", "Chr", "Pos", "Strand", "Score")
```

This therefore just renames the can_log_prob to score instead of using the calculated score, right?

**Comment by zakayuen** [comment]
Fixed in [7168f19](https://github.com/comprna/METEORE/commit/7168f19054177136749a5edc1b8aaf6a97c3f822)
