### ISSUE TITLE
guppy snakemake rocksdb error

### ISSUE THREAD

**Issue by lixiaopi1985** [comprna/METEORE#5]
Hi,

Thanks for developing this pipeline.

I encountered error running snakemake -s Guppy guppy_results/example_guppy-freq-perCG.tsv

It seems an error from importing rocksdb, it says undefined symbol

I installed rocksdb from the source using cmake and make, make install INSTALL_PATH=/usr outside conda environment.

----------------------------------------------
Another request is if it is possible to indicate conda version, python version, R version, etc, all requisites in each workflow? I basically encounter issues in each one just following the tutorial even in the conda environment. It has been a nightmare to debug for non advanced user like me. 

Thank you,

**Comment by zakayuen** [comment]
Sorry for the difficulties. Will indicate the specific package versions in each workflow.

Zaka

**Comment by zakayuen** [comment]
Hi @lixiaopi1985,

We have edited the guppy.yml, and all required packages including rocksdb should be installed correctly now. 

You can run it again with the new guppy.yml file. 

Please let me know if you have any questions.

Zaka
