### ISSUE TITLE
segmentation fault while runninc the combination_model_prediction (megalodon - nanopolish)

### ISSUE THREAD

**Issue by ligiamateiu** [comprna/METEORE#6]
Hey, 
I have only recently I found Meteore. I have run separately megalodon and nanopolish, but I used the scripts from meteore cu generate perRead-score.tsv for megalodon and nanopolish. The tsv files are big (69G and 31G, respectively). I have tried using only the common reads called by megalodon and nanopolish but still it failed. 
Do you think I should split the input files or do you have a better suggestion?

best,
Ligia

**Comment by zakayuen** [comment]
Hi,

The `combination_model_prediction.py` script will look for common reads in both tsv files and generate consensus predictions. There is no need to filter the reads beforehand. 

Could you paste the commands that you used and the error messages printed to the terminal?

Zaka

**Comment by ligiamateiu** [comment]
Hi,
The error was just the common c/c++ error :)  segmentation fault (core dumped) and no files were created.

Here is the command for the combined model
python combination_model_prediction.py  -i files_in.tsv -m default -o ont_results/combined_default_model.tsv

files_in.tsv contains 
megalodon	ont_results/megalodon_results/megalodon-perRead-score.tsv
nanopolish	ont_results/nanopolish_results/nanopolish-perRead-score.tsv


The head of both files looks like this 
ID	Pos	Strand	Score
8a3c8e56-4fe9-4a18-b6c9-339c3587e56b	111703456	-	-1.9101
8a3c8e56-4fe9-4a18-b6c9-339c3587e56b	111703380	-	0.940288


Thanks.
Ligia

**Comment by Akanksha2511** [comment]
Hi Ligia, 

Sorry for the late reply. Yes, it seems like file size and memory issue. We will update the script soon to handle the big files but for now, can you please try splitting the input files and see if it works. 

Thanks, 
Akanksha
