### ISSUE TITLE
module loading error - combination_model_prediction.py

### ISSUE THREAD

**Issue by ligiamateiu** [comprna/METEORE#8]
I wonder if this error is related with the python version when the saved models were created.

$python3 combination_model_prediction.py  -i files_in -m default -o results/combined_default_model.tsv

combination_model_prediction.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_file["Pos"][mask]=data_file["Pos"][mask]-1
Traceback (most recent call last):
  File "combination_model_prediction.py", line 77, in <module>
    main(mp,combine_file)
  File "combination_model_prediction.py", line 44, in main
    loaded_model = joblib.load(open(mp, 'rb'))
  File "/usr/local/lib/python3.8/dist-packages/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj)
  File "/usr/local/lib/python3.8/dist-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.8/pickle.py", line 1210, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.8/pickle.py", line 1526, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.8/pickle.py", line 1577, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

**Comment by Akanksha2511** [comment]
The model was saved in python3 and I suppose you are using the same, so should not be a problem. Looking at the error message it seems the sklearn library is not installed properly. Could you please try reinstalling it. 

Thanks, 
Akanksha

**Comment by ligiamateiu** [comment]
hey, it is not that, the problem is with loaded_model = joblib.load(open(mp, 'rb')). I've tried multiple versions and envs :) 
I think it has sth to do with this, version mismatch, while loading the pickled model in another file
https://github.com/scikit-learn/scikit-learn/issues/16570

I was thinking to create the model file, but I see that it is needed of a column "label" besides the ID, Pos, Strand and Score. What is that column?


Thanks,
Ligia

**Comment by Akanksha2511** [comment]
Hi sorry about the issue. Could you please try sklearn version 0.20.3.
Thanks, 
Akanksha

**Comment by ligiamateiu** [comment]
All good now :)
Thanks.
Ligia
