### ISSUE TITLE
per-site prediction from combined model format

### ISSUE THREAD

**Issue by unnatisonawala** [comprna/METEORE#9]
Hello,

Is there an easy way to convert the per-site prediction from the combined model to a bedgraph? I am a bit lost since the positions are over the entire genome rather than chromosomal coordinates. 
Thank you.

**Comment by unnatisonawala** [comment]
Hi,
From looking at the final tsv file a bit more, it looks like the Pos column actually only spans the length of the first chromosome. So I went back and looked at the files created for consensus prediction. Taking the nanopolish pipeline as an example: the final step takes the {sample}_nanopolish-log-perCG.tsv file (which has data from all chromosomes using Chr and Pos cols) and then formats it in R to just take Pos for the entire file. That would mix up all the chromosomes though. Am I missing something here?

**Comment by zakayuen** [comment]
Hi,

Sorry for the late reply. I am going to add an extra "Chr" column to the final tsv files for all pipelines. 

The reason why I only included the position information only is that we were using the _E.coli_ data which contains one circular chromosome only.

I'll fix this and let you know.

Zaka

**Comment by unnatisonawala** [comment]
Okay, that makes sense. I look forward to trying it again once you have fixed it. Thanks!

**Comment by zakayuen** [comment]
`Chr` is now added to the per-read output for all tools. See https://github.com/comprna/METEORE/commit/0c95904047eedbb0ee03a6c568a479b44138dfc1

I will modify the consensus script very soon. 

Zaka

**Comment by zakayuen** [comment]
The consensus script has been updated. `Chr` information is included in the output. Please give it a go.

Thank you for your patience.

Zaka
